import embedData from '@/data/embedVideos.json';
import type { Level, Video, VideoAttribution } from '@/types';

/**
 * YouTube-embed videos for the feed, generated by `npm run publish-embeds`
 * from the discovery pipeline (loro_video_candidates -> captions -> gloss).
 *
 * Static and in-repo on purpose: content ships with the code, is reviewable
 * in diffs, and needs no schema migration or n8n involvement. The row's
 * `id` is the raw YouTube id — it becomes the SRS video_id for words saved
 * from these slides, exactly like static ids do.
 *
 * The license split stays visible end to end: `attribution.license` is what
 * the CC BY chip renders from, and 'youtube' rows are embeds forever.
 */

type EmbedEntry = {
  id: string;
  youtubeId: string;
  creator: string;
  level: string;
  durationSeconds: number;
  thumbnailUrl: string;
  attribution: VideoAttribution;
  cues: Video['cues'];
  dictionary: Video['dictionary'];
};

const LEVELS: readonly Level[] = ['A1', 'A2', 'B1', 'B2'];
/** Same reasoning as lib/publishedVideos.ts: ungraded content slots mid-feed. */
const DEFAULT_LEVEL: Level = 'A2';

export const embedVideos: Video[] = (embedData as unknown as EmbedEntry[]).map(
  (entry) => ({
    id: entry.id,
    // No file — the slide renders the iframe player. Feed branches on
    // youtubeId before it ever touches src, so this never reaches a <video>.
    src: '',
    poster: entry.thumbnailUrl ?? '',
    creator: entry.creator,
    level: LEVELS.includes(entry.level as Level)
      ? (entry.level as Level)
      : DEFAULT_LEVEL,
    cues: entry.cues,
    dictionary: entry.dictionary,
    youtubeId: entry.youtubeId,
    durationSeconds: entry.durationSeconds,
    attribution: entry.attribution,
  })
);
