/**
 * THE BLUE WORDS' DIFFICULTY BANDS — generates packages/core/src/catalog/wordBands.ts.
 *
 * Radek, 2026-10-04: "it chooses super bad hard words or numbers … numbers it
 * shouldn't be at all". The bands used to be ~450 hand-picked words, and
 * everything else was "band 5". Twenty right answers put a user at level 5,
 * so from day two the blue blanks were whatever the hand lists missed:
 * "sonda = catheter", "vejiga = bladder", "lubricante", "escapular". At the
 * bottom they were pronouns and numbers ("te = you", "doscientos = 200").
 *
 * NOW THE BANDS ARE HOW SPOKEN SPANISH ACTUALLY RANKS, measured on Loro's own
 * videos: a word's rank is how many DIFFERENT CREATORS say it (then how many
 * videos). Creators, not occurrences, so one cooking channel saying "aceite"
 * forty times cannot make it common, and a word every creator uses ("tener",
 * "llegar", "lugar") rises to the top on its own. A word fewer than
 * MIN_CREATORS creators say is not in the table at all, and a word not in the
 * table is never a blue blank — that is what keeps "catheter" out.
 *
 * Only real vocabulary is counted: nouns, verbs, adjectives, adverbs. Never
 * grammar glue (glossary FUNCTION_WORDS), pronouns, names, fillers, or number
 * words. Keyed by the gloss lemma, so every form of "poder" is band 1.
 *
 *   node scripts/build-word-bands.mts      (re-run after a big catalog change)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { REPO_ROOT } from './lib/env.mts';
import { isProperName, lookupGloss, normalizeSurface } from '../packages/core/src/dictionary.ts';
import { isFunctionWord } from '../packages/core/src/glossary.ts';
import { numberWordBand } from '../packages/core/src/numerals.ts';
import type { Video } from '../packages/core/src/types.ts';

const OUT = path.join(REPO_ROOT, 'packages', 'core', 'src', 'catalog', 'wordBands.ts');
const SOURCES = ['embedVideos.json', 'collections.json'];

/** Said by at least this many different creators, or it is too niche to ask. */
const MIN_CREATORS = 3;
/** The last rank of each band (1-based, inclusive); band 5 is everything after. */
const BAND_ENDS = [150, 400, 700, 1000];
const CONTENT_POS = new Set(['noun', 'verb', 'adj', 'adv']);

const videos: Video[] = SOURCES.flatMap((f) =>
  JSON.parse(readFileSync(path.join(REPO_ROOT, 'data', f), 'utf8'))
);

const byLemma = new Map<string, { creators: Set<string>; videos: Set<string> }>();
for (const video of videos) {
  for (const cue of video.cues) {
    for (const word of cue.words) {
      const surface = normalizeSurface(word.text);
      if (!surface || isFunctionWord(surface)) continue;
      const gloss = lookupGloss(video, word.text);
      if (!gloss || !CONTENT_POS.has(gloss.pos.trim().toLowerCase())) continue;
      if (isProperName(word.text, gloss)) continue;
      const lemma = normalizeSurface(gloss.lemma || surface);
      if (!/^\p{L}+$/u.test(lemma) || lemma.length < 2) continue;
      if (isFunctionWord(lemma) || numberWordBand(lemma) !== null || numberWordBand(surface) !== null) continue;
      if (/\d/.test(gloss.glosses.en ?? '')) continue;
      let entry = byLemma.get(lemma);
      if (!entry) byLemma.set(lemma, (entry = { creators: new Set(), videos: new Set() }));
      entry.creators.add(video.creator);
      entry.videos.add(video.id);
    }
  }
}

const ranked = [...byLemma]
  .filter(([, e]) => e.creators.size >= MIN_CREATORS)
  .sort(
    ([a, x], [b, y]) =>
      y.creators.size - x.creators.size || y.videos.size - x.videos.size || a.localeCompare(b)
  )
  .map(([lemma]) => lemma);

const bands: Record<string, number> = {};
ranked.forEach((lemma, i) => {
  const end = BAND_ENDS.findIndex((last) => i < last);
  bands[lemma] = end === -1 ? BAND_ENDS.length + 1 : end + 1;
});

const counts = [1, 2, 3, 4, 5].map((b) => Object.values(bands).filter((x) => x === b).length);
writeFileSync(
  OUT,
  `/**\n * GENERATED by scripts/build-word-bands.mts — do not edit by hand. Lemma →\n * difficulty band 1-5, ranked by how many of Loro's creators say it\n * (${videos.length} videos, ${ranked.length} words). Not listed = never a blue blank.\n */\nexport const WORD_BANDS: Readonly<Record<string, number>> = ${JSON.stringify(bands)};\n`
);
console.log(`${videos.length} videos → ${ranked.length} words; per band ${counts.join(' / ')}`);
