-- The catalog snapshot bucket.
--
-- loro_catalog_videos (20260804000000) is the queryable copy of the catalog.
-- This bucket is how a CLIENT actually gets it: one immutable JSON object
-- holding the whole Video[], fetched in a single CDN GET (~0.9MB gzipped)
-- rather than 216 PostgREST rows. Generated by scripts/publish-catalog.mts;
-- nothing reads it yet.
--
-- TWO OBJECT KINDS, and the difference between them is the whole design:
--
--   catalog/<hash>.json   IMMUTABLE. Named by the sha256 of its own bytes, so
--                         the name IS the version and the same content can
--                         never mean two different things. Never overwritten:
--                         the publisher uploads with upsert disabled, and a
--                         collision means the content is already there. Safe
--                         to cache forever, which is what makes this cheap.
--   catalog/latest.json   MUTABLE, tiny, and the ONLY object that ever
--                         changes: {hash, count, generatedAt}. A client reads
--                         this, compares the hash to what it has cached, and
--                         downloads the blob only when it differs.
--
-- Cache lifetimes are set per object by the uploader (the SDK's cacheControl),
-- not here: a year for the immutable blobs, a minute for the pointer.
--
-- WHY A SEPARATE BUCKET rather than a folder in loro-videos: that bucket's
-- write policies are gated on being an APPROVED creator, because it holds
-- creator uploads. This holds editorial content with no owner, written only by
-- the service role. Different policies, so different buckets — the same
-- reasoning the avatars bucket (20260723000000) was split out on.
--
-- Idempotent (on conflict do nothing / drop-and-recreate policy): replaying
-- yields the same end state.

insert into storage.buckets (id, name, public)
values ('loro-catalog', 'loro-catalog', true)
on conflict (id) do nothing;

-- Public read: this is the catalog the app already ships inside its web
-- bundle, so it is public by definition. Anonymous users are the majority of
-- everyone who will ever fetch it — the client needs no session to boot.
drop policy if exists "public read catalog snapshots" on storage.objects;
create policy "public read catalog snapshots"
  on storage.objects for select
  using (bucket_id = 'loro-catalog');

-- NO insert / update / delete policy, deliberately. Under RLS an operation
-- with no policy is denied, so no anon or authenticated key can write a single
-- object here; scripts/publish-catalog.mts (service role, which bypasses RLS)
-- is the only writer. Same posture as loro_catalog_videos itself, and it is
-- what keeps "immutable" a property of the bucket rather than a promise made
-- by one script.
